name: Create Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # to allow getting previous tags
      
      - name: Exit if not on main branch
        if: endsWith(github.ref, 'refs/heads/main') == false
        run: exit -1


      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}

      - run: npm install -g npm
      - run: npm ci

      # Commit the new version to the repo 
      - name: Commit new version
        run: |
          git checkout main 
          git config --local user.email "arihershowitz@gmail.com"
          git config --local user.name "Ari Hershowitz"
          git add package.json package-lock.json
          git commit -m "Update version to $(echo $GITHUB_REF | cut -d / -f 3 | sed 's/^v//')"
          git push

      #- run: npm run build
      #- run: npm test
      - run: zip -r lrc-annotate.zip transforms/** styles/** README.md
      - name: Generate Changelog
        run: |
          export VERSION=$(git tag --sort=-committerdate | head -1)
          export PREVIOUS_VERSION=$(git tag --sort=-committerdate | head -2 | awk '{split($0, tags, "\n")} END {print tags[1]}')
          export CHANGES=$(git log --pretty="- %s" $VERSION...$PREVIOUS_VERSION)
          printf "# 🎁 Release notes (\`$VERSION\`)\n\n## Changes\n\n$CHANGES\n\n## Metadata\n\n\`\`\`csv\nThis version -------- $VERSION\nPrevious version ---- $PREVIOUS_VERSION\nTotal commits ------- $(echo "$CHANGES" | wc -l)\n\`\`\`\n" > ${{ github.workspace }}-CHANGELOG.md
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.md
          files: lrc-annotate.zip

      #- name: Create GitHub Release PR
      #  run: npx release-please github-release --repo-url https://github.com/defrances/LRC-Annotate-XSLT/tree/LCD-77-debug-branch-main --target-branch LCD-77-debug-branch-main --branch LCD-77-debug-branch