name: Run Main Workflows

on:
  push:
    branches:
      - main

jobs:
  run-first-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run first workflow
        run: |
          # Run the first workflow
          # Replace 'path/to/release-please.yml' with the actual path to your first YAML file
          echo "Running first workflow..."
          github/workflows/release-please.yml
        continue-on-error: true

      - name: Trigger second workflow
        if: ${{ success() }}
        run: |
          echo "Triggering second workflow..."
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/owner/repo/dispatches \
            -d '{"event_type": "run-second-workflow"}'
