name: Run Workflows

on:
  push:
    branches:
      - main

jobs:
  run-first-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run first workflow
        run: |
          # Run the first workflow
          # Replace 'path/to/first-workflow.yml' with the actual path to your first YAML file
          echo "Running first workflow..."
          .github/workflows/firststep/release-please.yml
        continue-on-error: true

      - name: Trigger second workflow
        if: ${{ success() }}
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data } = await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_file: '.github/workflows/secondstep/publish-npm-package.yml' 
            });
            console.log(`Second workflow triggered: ${data.status}`);
